/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonCalendar: typeof import('./src/views/common/common-calendar.vue')['default']
    CommonCascader: typeof import('./src/views/common/common-cascader.vue')['default']
    CommonList: typeof import('./src/views/common/common-list.vue')['default']
    CommonSearch: typeof import('./src/views/common/common-search.vue')['default']
    CommonSheet: typeof import('./src/views/common/common-sheet.vue')['default']
    CommonTabs: typeof import('./src/views/common/common-tabs.vue')['default']
    CommonTitle: typeof import('./src/views/common/common-title.vue')['default']
    CustomList: typeof import('./src/views/common/custom-list.vue')['default']
    EmptyPage: typeof import('./src/views/common/empty-page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThirdFilter: typeof import('./src/views/common/third-filter.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCascader: typeof import('vant/es')['Cascader']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSticky: typeof import('vant/es')['Sticky']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
