/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonBar: typeof import('./src/views/common/common-bar.vue')['default']
    CommonCalendar: typeof import('./src/views/common/common-calendar.vue')['default']
    CommonField: typeof import('./src/views/common/common-field.vue')['default']
    CommonList: typeof import('./src/views/common/common-list.vue')['default']
    CommonRing: typeof import('./src/views/common/common-ring.vue')['default']
    CommonSheet: typeof import('./src/views/common/common-sheet.vue')['default']
    CommonTabs: typeof import('./src/views/common/common-tabs.vue')['default']
    CommonTitle: typeof import('./src/views/common/common-title.vue')['default']
    EmptyPage: typeof import('./src/views/common/empty-page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
